name = "FUST"
version = "0.1.0"
keywords = ["math", "physics"]
defaultTargets = ["FUST"]

[leanOptions]
pp.unicode.fun = true
autoImplicit = false
relaxedAutoImplicit = false
weak.linter.mathlibStandardSet = true
maxSynthPendingDepth = 3

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev   = "v4.26.0"

[[require]]
name = "PhysLean"
git  = "https://github.com/HEPLean/PhysLean.git"
rev   = "v4.26.0"

[[require]]
name = "doc-gen4"
scope = "leanprover"
rev   = "v4.26.0"

[[lean_lib]]
name = "FUST"
